for i in 1..10
  puts i
end
```I hope these examples help you learn the basics of Ruby! Let me know if you have any questions.:){style="text-decoration: underline;"}*[Learn more about the `gets` method here.](https://www.ruby-lang.org/en/documentation/keriora/1.9.3/Kernel/)*
*[Learn more about the `chomp` method here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-chomp)*
*[Learn more about arrays here.](https://ruby-doc.org/core-2.7.0/Array.html)*
*[Learn more about hashes here.](https://ruby-doc.org/core-2.7.0/Hash.html)*
*[Learn more about the `upcase` and `downcase` methods here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-upcase)*
*[Learn more about the `length` method here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-length)*
*[Learn more about the `%` operator here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-remainder)*
*[Learn more about the `if-else` statement here.](https://ruby-doc.org/core-2.7.0/doc/syntax/control_expressions_rdoc.html#label-if)*
*[Learn more about the `for` loop here.](https://ruby-doc.org/core-2.7.0/doc/syntax/control_expressions_rdoc.html#label-for)*
*[Learn more about the `..` operator here.](https://ruby-doc.org/core-2.7.0/doc/syntax/literals_rdoc.html#label-Range+ Literals)*

*[Learn more about the `puts` method here.](https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-puts)*
*[Learn more about the `print` method here.](https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-print)*
*[Learn more about variables here.](https://ruby-doc.org/core-2.7.0/doc/syntax/variables_rdoc.html#label-Variables+ and+ Constants)*
*[Learn more about the `gets` method here.](<https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-gets>)*
*[Learn more about the `chomp` method here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-chomp)*
*[Learn more about the `+` operator here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-+)*
*[Learn more about the `*` operator here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-*)
*[Learn more about the `-` operator here.](https://ruby-doc.org/core-2.7.0/String.html#method-i- -)*
*[Learn more about the `/` operator here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-/)*
*[Learn more about the `**` operator here.](https://ruby-doc.org/core-2.7.0/Numeric.html#method-i-**)
*[Learn more about the `%` operator here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-remainder)
*[Learn more about the `puts` method here.](https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-puts)
*[Learn more about the `print` method here.](https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-print)
*[Learn more about variables here.](https://ruby-doc.org/core-2.7.0/doc/syntax/variables_rdoc.html#label-Variables+ and+ Constants)
*[Learn more about the `gets` method here.](https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-gets)
*[Learn more about the `chomp` method here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-chomp)
*[Learn more about arrays here.](https://ruby-doc.org/core-2.7.0/Array.html)
*[Learn more about hashes here.](https://ruby-doc.org/core-2.7.0/Hash.html)
*[Learn more about the `upcase` and `downcase` methods here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-upcase)
*[Learn more about the `length` method here.](https://ruby-doc.org/core-2.7.0/String.html#method-i-length)
*[Learn more about the `if-else` statement here.](https://ruby-doc.org/core-2.7.0/doc/syntax/control_expressions_rdoc.html#label-if)
*[Learn more about the `for` loop here.](https://ruby-doc.org/core-2.7.0/doc/syntax/control_expressions_rdoc.html#label-for)
*[Learn more about the `..` operator here.](https://ruby-doc.org/core-2.7.0/doc/syntax/literals_rdoc.html#label-Range+ Literals)*[Learn more about the `<<` operator here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-<<)
*[Learn more about the `push` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-push)*[Learn more about the `.each` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-each)
*[Learn more about the `.select` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-select)
*[Learn more about the `==` operator here.](https://ruby-doc.org/core-2.7.0/Comparable.html#method-i-3D-3D)
*[Learn more about the `<<` operator here.](https://ruby-doc.org/core-2.7.0/Array.*[Learn more about the `<<` operator here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-<<)
*[Learn more about the `shift` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-shift)
*[Learn more about the `push` method here.](<https://ruby-doc.org/core-2.7.0/Array.html#method-i-push>)
*[L
*[Learn more about the `pop` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-pop)
*[Learn more about the `shift` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-shift)
*[Learn more about the `unshift` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-unshift)
*[Learn more about the `index` method here.](https://ruby-doc.org/core-2.7.0/Array.html#earn more about the `pop` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-pop)
*[Learn more about the `keys` method here.](https://ruby-doc.org/core-2.7.0/Hash.html#method-i-keys)
*[Learn more about the `values` method here.](https://ruby-doc.org/core-html#method-i-3C-3C)
*[Learn more about the `.include?` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-include-3F)
*[Learn more about the `.pop` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-pop)
*[Learn more about the `.shift` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-shift)
*[Learn more about the `.push` method here.](https://ruby-doc.org/core-2.7.0/method-i-index)
*[Learn more about the `include?` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-include-3F)
*[Learn more about the `each` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-each)
*[Learn more about the `map` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-map)
*[Learn more about the `select` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#2.7.0/Hash.html#method-i-values)
*[Learn more about the `include?` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-include-3F)
*[Learn more about the `member?` method here.](https://ruby-method-i-select)
*[Learn more about the `count` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-count)
*[Learn more about the `sort` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-push)
*[Learn more about the `.unshift` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-unshift)
*[Learn more about the `.sort` method here.](<https://ruby-doc.org/core-2.7.0/Array.html#method-i-sort>)\*(Note: the `Arrays` and `Hashes` links in the examples are for the current version of Ruby, which is 2.7 as of this writing. However, the version number may change in the future, so it is recommended to check the Ruby documentation for thedoc.org/core-2.7.0/Hash.html#method-i-member-3F)
*[Learn more about the `<=>` operator here.](https://ruby-doc.org/core-2.7.0/Comparable.html#method-i-3C-3D)
*[Learn more about the `sort` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sort)
*[Learn more about the `sort_by` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sort_by)
*[Learn more about the `each` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-each)
*[Learn more about the `map` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-map)
*[Learn more about the `select` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-select)
*[Learn more about the `reject` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-reject)
*[Learn more about the `count` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-count)
*[Learn more about the `any?` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-any-3F)
*[Learn more about the `all?` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-all-3F)
*[Learn more about the `none?` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-none-3F)
*[Learn more about the `sum` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sum)
*[Learn more about the `inject` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-inject)
*[Learn more about the `group_by` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-group_by)
*[Learn more about the `min` and `min_by` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-min)
*[Learn more about the `max` and `max_by` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-max)
*[Learn more about the `first` and `take` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-first)
*[Learn more about the `last` and `drop` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-last)
*[Learn more about the `zip` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-zip)
*[Learn more about the `transpose` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-transpose)
*[Learn more about the `flatten` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-flatten)
*[Learn more about the `slice` and `slice_when` methods here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-slice_when)
*[Learn more about the `chunk` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-chunk)
*[Learn more about the `each_cons` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-each_cons)
*[Learn more about the `each_slice` method here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-each_slice)
*[Learn more about the `each_with_index` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-each_with_index)
*[Learn more about the `each_with_object` method here.](<https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-each_with_object>)
*[Learn more about the `.map` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-map)
*[Learn more about the `.map_with_index` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-map_with_index)
*[Learn more about the `.reduce` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-reduce)
*[Learn more about the `.filter_map` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-filter_map)
*[Learn more about the `.flat_map` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-flat_map)
*[Learn more about the `.each_with_object` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-each_with_object)
*[Learn more about the `.cycle` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-cycle)
*[Learn more about the `.lazy` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-lazy)
*[Learn more about the ` to_a` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-to_a)
*[Learn more about the `.sum` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sum)
*[Learn more about the `.min` and `min_by` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-min)
*[Learn more about the `.max` and `max_by` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-max)
*[Learn more about the `.minmax` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-minmax)
*[Learn more about the `.minmax_by` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-minmax_by)
*[Learn more about the `.sort` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sort)
*[Learn more about the `.sort_by` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sort_by)
*[Learn more about the `.sort_by!` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sort_by-21)
*[Learn more about the `.sort!` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-sort-21)
*[Learn more about the `.reverse` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-reverse)
*[Learn more about the `.reverse_each` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-reverse_each)
*[Learn more about the `.each_with_index` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-each_with_index)
*[Learn more about the `.each_with_object` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#)
*[Learn more about the `.group_by` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-group_by)
*[Learn more about the `. chunk` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-chunk)
*[Learn more about the `.partition` method here.](<https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-partition>)
*[Learn more about the `.slice_when` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-slice_when)
*[Learn more about the `.slice` and ` slice_after` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-slice_after)
*[Learn more about the `.take` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-take)
*[Learn more about the `.drop` method here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-drop)
*[Learn more about the `.first` and `.last` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-first)
*[Learn more about the `.detect` and `find` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-detect)
*[Learn more about the`.find_index` and `find` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-find_index)
*[Learn more about the `.select` and `.filter` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-select)
*[Learn more about the `.reject` and `.filter_map` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-reject)
*[Learn more about the `.upto` and `count_up_to` methods here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-upto)
*[Learn more about the `.downto` and `count_down_from` methods here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-downto)
*[Learn more about the `.step` and `each_step` methods here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-step)
*[Learn more about the `.times` and `loop` methods here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-times)
*[Learn more about the `.cycle` and `looper` methods here.](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-cycle)
*[Learn more about the `.each` and `loop_over` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-each)
*[Learn more about the `.map` and `collect` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-map)
*[Learn more about the `.filter` and `select` methods here.](<https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-filter>)
*[Learn more about the `.reject` and `delete_if` methods here.](<https://ruby-doc.org/core-2.7.0/Array.html#method-i-reject>)
*[Learn more about the `.all?` and `each` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-all-3F)
*[Learn more about the `.any?` and `any?` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-any-3F)
*[Learn more about the `.none?` and `none?` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-none-3F)
*[Learn more about the `.all?` and `none?` methods here.](https://ruby-doc.org/core-2.7.0/Array.html#method-i-all-3F)
*[Learn more about the `.all?` and `none?` methods here.](https://ruby-doc.org/core-2.7.0/Range.html#method-i-all-3F)
*[Learn more about the `.any?` and `any?` methods here.](https://ruby-doc.org/core-2.7.0/Range.html#method-i-any-3F)
*[Learn more about the `.none?` and `none?` methods here.](https://ruby-doc.org/core-2.7.0/Range.html#method-i-none-3F)
*[Learn more about the `.many?` and `many?` methods here.](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-many-3F)
